### ISSUE TITLE
Move `single_sign` to `Key`

### ISSUE THREAD

**Issue by SAYaghoubnejad** [SAYaghoubnejad/pyfrost#20]
If the only use of `single_sign` is in `Key`, then move it to `Key` and make it private.

**Comment by mchitgarha78** [comment]
The function `single_sign` has been moved to the `Key` class and made private.

**Comment by mchitgarha78** [comment]
Another use of the `single_sign` is in `pyfrost/tests/test_utils.py` file. The function has been returned to its first place in `frost.py` file.
