### ISSUE TITLE
Use strip instead of slicing

### ISSUE THREAD

**Issue by SAYaghoubnejad** [SAYaghoubnejad/pyfrost#5]
To remove the `0x` part of the hash, use strip instead of `[2:]`.

**Comment by mchitgarha78** [comment]
In some particular cases, We may have problem. e.g. assume that the text is :
```python
text = '0x0f952fb36da0a191251cd9cdf37c8d57d78da4aaae2d9950f2c280bea23e794dd4b0619e72b231b8200998d77c536af38566c08bc26cbe44c1c08ac5f26b77c4'
```
If we want to use `lstrip` method, it drops three characters instead of two characters so that the result is false.

**Comment by SAYaghoubnejad** [comment]
Use `text.replace('0x', '')` instead.
